name: Deployment Exercise 2
on: [push]
jobs:
  Lint:
    runs-on: ubuntu_latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  Test:
    needs: [Lint]
    runs-on: ubuntu_latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run test
  Deploy:
    needs: [Test]
    runs-on: ubuntu_latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
